---
title: "intervencion"
output: pdf_document
date: "2022-10-08"
---

\fontsize{15}{15}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(LaplacesDemon)
library(tidyverse)
options(digits=4)
```

```{r}
#A. Posterior en t=19
m19 <- c(1.5, 1.8, -0.7)
C19 <- matrix(c(0.00002, 0.00001, -0.00002, 0.00001, 0.00003, -0.00001, -0.00002, 
                -0.00001, 0.00002), ncol = 3)

#Valores conocidos de G20 y W20
G20 <- matrix(c(1.001, 0, 0, 0, 1, 0, 0, 0, 1), ncol=3)
G30 <- matrix(c(1.001, 0, 0, 0, 1, 0, 0, 0, 1), ncol=3)
W20 <- matrix(c(0.00001, 0, 0, 0, 0.00001, -0.00001, 0, -0.00001, 0.00005), ncol=3)
W30 <- matrix(c(0.00001, 0, 0, 0, 0.00001, -0.00001, 0, -0.00001, 0.00005), ncol=3)
#B. Priori de parámetros en t=20
a20 <- G20 %*% m19
R20 <- G20 %*% C19 %*% t(G20) + W20
a20
R20

a20_int <- c(1.501, 2.3, -0.7)
R20_int <- matrix(c(3.004e-05, 1.001e-05, -2.002e-05, 1.001e-05, 0.005, 
                    -2.000e-05, -2.002e-05, -2.000e-05, 7.000e-05), ncol = 3)
```



```{r}
F20 <- c(1, 6.06093, 4.51018) #Variables explicativas en t=20. El 1 es para
                              #agregar el intercepto
S19 <- 0.00005 # Estimación de V en T=19
n19 <- 19.5 # Grados de libertad
#C. Pronóstico a un periodo.
f20 <- as.numeric(t(F20) %*% a20_int)
Q20 <- as.numeric(t(F20) %*% R20_int %*% F20 + S19)
f20
Q20
```

```{r}
c(qst(0.025, nu = n19, mu = f20, sigma = sqrt(Q20)),
  qst(0.975, nu = n19, mu = f20, sigma = sqrt(Q20)))
```

```{r}
#Valor observado de Y20:
Y20 <- 11.6
#D. Posterior en t=20
A20 <- R20_int %*% F20 / Q20
e20 <- Y20-f20
m20 <- a20_int + A20 %*% e20
n20 <- n19 + 1
S20 <- S19 + (S19/n20)*(e20^2/Q20-1)
C20 <- (S20/S19)*(R20_int-A20 %*% t(A20) * Q20)
m20
C20
```

Distribuciones filtradas

```{r}
#U20 <- chol(R20_int)
#Z20 <- chol(R20)
#K20 <- U20 %*% solve(Z20)
#G20_int <- K20 %*% G20
#W20_int <- K20 %*% W20 %*% t(K20)
```


```{r}
#B19 <- C19 %*% t(G20_int) %*% solve(R20_int)
#a20_menos_1 <- m19 + B19 %*% (m20 - a20_int)
#R20_menos_1 <- C19 - B19 %*% (C20 - R20_int) %*% solve(B19)

#a20_menos_1

#S20/S19 * R20_menos_1
```

```{r}
#F19 <- c(1, 6.05563	, 4.53957) #Variables explicativas en t=19. El 1 es para
                              #agregar el intercepto
#t(F19) %*% a20_menos_1

#S20/S19 * t(F19) %*% R20_menos_1 %*% F19
```

Mas de una obs.

```{r}
datos_ej <- freeny %>% 
  mutate(intercept = 1) %>% 
  slice(20:n()) %>% 
  dplyr::select(y, intercept, income.level, price.index) %>% 
  mutate(y = ifelse(y>=9.6, y+0.5,y))
#Metemos ruido
set.seed(2)
datos_ej$y[11:20] <- datos_ej$y[11:20] + rnorm(10,0,0.05)
datos_ej
```


```{r}
#Se asume que Gt, Vt y Wt son ctes conocidas para toda t.
actualizacion_V_desc <- function(datos, m0, C0, G, W, S0, n0, lista_interv){
  
  error_varianza <- function(x) {
  if(any (diag(x)<0)) stop ('Elementos del parametro de escala o varianzas deben ser positivos')
  }
  
  mt_menos_1 <- m0
  Ct_menos_1 <- C0
  St_menos_1 <- S0
  nt_menos_1 <- n0
  lista_at <- list()
  lista_Rt <- list()
  lista_ft <- list()
  lista_Qt <- list()
  lista_mt <- list()
  lista_Ct <- list()
  lista_CI <- list()
  lista_CI_inf <- list()
  lista_CI_sup <- list()
  lista_St <- list()
  interv <- F
  for(t in 1:length(datos$y)){

    if(t %in% lista_interv$t_int){
      at <- lista_interv$at_int[[match(t,list_interv$t_int)]]
      Rt <- lista_interv$Rt_int[[match(t,list_interv$t_int)]]
      interv <- T
    } else {
      at <- G %*% mt_menos_1
      Rt <- G %*% Ct_menos_1 %*% t(G) + W
    }
    
    Ft <- as.numeric(datos[t, 2:4])
    ft <- t(Ft) %*% at
    Qt <- t(Ft) %*% Rt %*% Ft + St_menos_1
    CI <- c(qst(0.025, nu = nt_menos_1, mu = ft, sigma = sqrt(Qt)),
            qst(0.975, nu = nt_menos_1, mu = ft, sigma = sqrt(Qt)))
    CI_inf <- CI[1]
    CI_sup <- CI[2]
    Yt <- datos[t,1]
    At <- Rt %*% Ft %*% solve(Qt)
    et <- Yt-ft
    mt <- at + At %*% et
    nt <- nt_menos_1 + 1
    St <- as.numeric(St_menos_1 + (St_menos_1/nt) * (et^2 %*% solve(Qt) - 1))
    Ct <- (St/St_menos_1)*(Rt - At %*% Qt %*% t(At))
    
    error_varianza(Rt)
    error_varianza(St)
    error_varianza(Ct)
    
    lista_at[[t]] <- at
    lista_Rt[[t]] <- Rt
    lista_ft[[t]] <- ft
    lista_Qt[[t]] <- Qt
    lista_CI[[t]] <- CI
    lista_CI_inf[[t]] <- CI_inf
    lista_CI_sup[[t]] <- CI_sup
    lista_mt[[t]] <- mt
    lista_Ct[[t]] <- Ct
    lista_St[[t]] <- St
    mt_menos_1 <- mt
    Ct_menos_1 <- Ct
    nt_menos_1 <- nt
    St_menos_1 <- St
    
    interv <- F
  }
  return(list("at" = lista_at,  "Rt" = lista_Rt,  "ft" = lista_ft, 
              "Qt" = lista_Qt, "CI" = lista_CI, "CI_inf" = lista_CI_inf, 
              "CI_sup" = lista_CI_sup, "mt" = lista_mt, "Ct" = lista_Ct,
              "St" = lista_St))
}
```

```{r}
res_dlm_no_int <- actualizacion_V_desc(datos_ej, m19, C19, G20, W20, S19, n19, list())
```

```{r}
a30_int <- res_dlm_no_int$at[[11]] %>% as_vector()
a30_int[2] <- 1.9
R30_int <- res_dlm_no_int$Rt[[11]]
R30_int[2,2] <- 0.0002
list_interv <- list("t_int" = list(11), "at_int" = list(a30_int), 
     "Rt_int" = list(R30_int))
```

```{r}
res_dlm <- actualizacion_V_desc(datos_ej, m19, C19, G20, W20, S19, n19, list_interv)
list_interv$at_int[[match(11,list_interv$t_int)]]
```



```{r}
df_graficas <- data.frame("fecha" = datos_ej %>% row.names(), "y_real" = datos_ej$y, 
           "y_pronostico" = res_dlm$ft %>% unlist(), "CI_inf" = res_dlm$CI_inf %>% unlist(),
           "CI_sup" = res_dlm$CI_sup %>% unlist()) %>% 
  mutate(fecha = as.numeric(fecha))
```


```{r}
ggplot(data = df_graficas, aes(x = fecha)) +
  geom_point(aes(y = y_real, shape = "Observaciones"), size = 2) +
  geom_line(aes(y = y_pronostico, color = 'Pronósticos'), size = 1) +
  geom_line(aes(y = CI_inf), color = "blue", alpha = 0.3) +
  geom_line(aes(y = CI_sup), color = "blue", alpha = 0.3) + 
  geom_ribbon(aes(ymax = CI_sup, ymin = CI_inf, fill = 'Intervalo al 95%'), alpha = 0.3) +
  theme_bw() +
  scale_colour_manual(
    name = "", values = c("Intervalo al 95%" = "transparent",
                          "Pronósticos" = "black")) +
  scale_fill_manual(
    name = "",  values = c("Intervalo al 95%" = "blue",
                           "Pronósticos" = "transparent")) +
  theme(legend.position = "bottom") +
  labs(shape = "") +
  ylab('Ventas') +
  xlab('Fecha') +
  theme(axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title = element_text(size = 22),
        legend.text = element_text(size=20)) 

ggsave(filename = "graphs/teoria/intervencion/actualizacion_interv.png", width = 11.7, height = 6)
```

```{r}
df_St <- data.frame(res_dlm$St %>% unlist(), fecha = df_graficas$fecha) %>% 
  rename(St = 1)
```

```{r}
ggplot(df_St, aes(x=fecha, y = St)) +
  geom_line() +
  theme_bw()  +
  ylab("St") +
  xlab("Fecha")
```

```{r}
df_params <- data.frame(reduce(res_dlm$mt, cbind) %>% t(), fecha = df_graficas$fecha)  %>% 
  rename(Intercepto = X1, Ingreso = X2, Precio = X3) %>% 
  pivot_longer(names_to = "parametro", values_to = "valor", 
               cols = c(Intercepto, Ingreso, Precio))

```


```{r}
ggplot(df_params, aes(x=fecha, y = valor)) +
  geom_line() +
  facet_wrap(~parametro, nrow = 3, scales = "free") +
  theme_bw()  +
  ylab("Valor") +
  xlab("Fecha") +
  theme(axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title = element_text(size = 22),
        strip.text = element_text(size=20)) 

#ggsave(filename = "graphs/teoria/actualizacion/parametros.png", width = 11.7, height = 6)
```



```{r}
df_graficas_no_int <- data.frame("fecha" = datos_ej %>% row.names(), "y_real" = datos_ej$y, 
           "y_pronostico" = res_dlm_no_int$ft %>% unlist(), "CI_inf" = res_dlm_no_int$CI_inf %>% unlist(),
           "CI_sup" = res_dlm_no_int$CI_sup %>% unlist()) %>% 
  mutate(fecha = as.numeric(fecha))
```


```{r}
ggplot(data = df_graficas_no_int, aes(x = fecha)) +
  geom_point(aes(y = y_real, shape = "Observaciones"), size = 2) +
  geom_line(aes(y = y_pronostico, color = 'Pronósticos'), size = 1) +
  geom_line(aes(y = CI_inf), color = "blue", alpha = 0.3) +
  geom_line(aes(y = CI_sup), color = "blue", alpha = 0.3) + 
  geom_ribbon(aes(ymax = CI_sup, ymin = CI_inf, fill = 'Intervalo al 95%'), alpha = 0.3) +
  theme_bw() +
  scale_colour_manual(
    name = "", values = c("Intervalo al 95%" = "transparent",
                          "Pronósticos" = "black")) +
  scale_fill_manual(
    name = "",  values = c("Intervalo al 95%" = "blue",
                           "Pronósticos" = "transparent")) +
  theme(legend.position = "bottom") +
  labs(shape = "") +
  ylab('Ventas') +
  xlab('Fecha') +
  theme(axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title = element_text(size = 22),
        legend.text = element_text(size=20)) 

ggsave(filename = "graphs/teoria/intervencion/actualizacion_no_interv.png", width = 11.7, height = 6)
```


```{r}
#Se pasan manualmente las G historicas en G, las de intervencion se calculan
suavizamiento_V_desc <- function(datos, G, nt, lista_interv){
  
  error_varianza <- function(x) {
  if(any (diag(x)<0)) stop ('Elementos del parametro de escala o varianzas deben ser positivos')
  }
  
  lista_ft_k_filt <- list()
  lista_at_k_filt <- list()
  lista_Rt_k_filt <- list()
  lista_resp_med_esc <- list()
  lista_CI_inf <- list()
  lista_CI_sup <- list()
  
  #Se calculan las distribuciones filtradas para k = T
  at_k_filt_mas_1 <- res_dlm$mt[[length(datos$y)]]
  Rt_k_filt_mas_1 <- res_dlm$Ct[[length(datos$y)]]
  St <- res_dlm$St[[length(datos$y)]]
  
  Ft <- as.numeric(datos[length(datos$y), 2:4])
  lista_ft_k_filt[[length(datos$y)]] <- t(Ft) %*% at_k_filt_mas_1
  lista_at_k_filt[[length(datos$y)]] <- at_k_filt_mas_1
  lista_Rt_k_filt[[length(datos$y)]] <- Rt_k_filt_mas_1
  lista_resp_med_esc[[length(datos$y)]] <- t(Ft) %*% Rt_k_filt_mas_1 %*% Ft
  lista_CI_inf[[length(datos$y)]] <- qst(0.025, nu = nt, mu = lista_ft_k_filt[[length(datos$y)]],
                                         sigma = sqrt(lista_resp_med_esc[[length(datos$y)]]))
  lista_CI_sup[[length(datos$y)]] <- qst(0.975, nu = nt, mu = lista_ft_k_filt[[length(datos$y)]],
                                         sigma = sqrt(lista_resp_med_esc[[length(datos$y)]]))
  interv <- F
  
  error_varianza(Rt_k_filt_mas_1)
  error_varianza(St)
  
  for(i in length(datos$y):2){
    #Se calculan las distribuciones filtradas para i-1. De lo mas reciente a lo mas viejo
    
    if(i %in% lista_interv$t_int){
      at_int <- lista_interv$at_int[[match(i,list_interv$t_int)]]
      Rt_int <- lista_interv$Rt_int[[match(i,list_interv$t_int)]]
      Rt<- res_dlm_no_int$Rt[[i]]
      Ut <- t(chol(Rt_int))
      Zt <- t(chol(Rt))
      Kt <- Ut %*% solve(Zt)
      Gt_int <- Kt %*% G
      interv <- T
    }
    
    Ct_k <- res_dlm$Ct[[i-1]]
    Rt_k_mas_1 <- res_dlm$Rt[[i]]
    mt_k <- res_dlm$mt[[i-1]]
    at_k_mas_1 <- res_dlm$at[[i]]
    St_k_mas_1 <- res_dlm$St[[i]]
    St_k <- res_dlm$St[[i-1]]
    
    Bt_k <- Ct_k %*% t(`if`(interv,Gt_int, G)) %*% solve(Rt_k_mas_1)
    at_k_filt <- mt_k + Bt_k %*% (at_k_filt_mas_1 - at_k_mas_1)
    Rt_k_filt <- Ct_k + Bt_k %*% (Rt_k_filt_mas_1 - Rt_k_mas_1) %*% t(Bt_k)
    params_esc <- (St/St_k)*Rt_k_filt
    
    Ft_k <- as.numeric(datos[i-1, 2:4])
    ft_k_filt <- t(Ft_k) %*% at_k_filt
    resp_med_esc <- (St/St_k)*(t(Ft_k) %*% Rt_k_filt %*% Ft_k)
    CI <- c(qst(0.025, nu = nt, mu = ft_k_filt, sigma = sqrt(resp_med_esc)),
            qst(0.975, nu = nt, mu = ft_k_filt, sigma = sqrt(resp_med_esc)))
    
    error_varianza(Rt_k_mas_1)
    error_varianza(Ct_k)
    error_varianza(St_k_mas_1)
    error_varianza(St_k)
    error_varianza(Rt_k_filt)
    
    lista_ft_k_filt[[i-1]] <- ft_k_filt
    lista_at_k_filt[[i-1]] <- at_k_filt
    lista_Rt_k_filt[[i-1]] <- Rt_k_filt
    lista_resp_med_esc[[i-1]] <- resp_med_esc
    lista_CI_inf[[i-1]] <- CI[1]
    lista_CI_sup[[i-1]] <- CI[2]
    
    at_k_filt_mas_1 <- at_k_filt
    Rt_k_filt_mas_1 <- Rt_k_filt
    interv <- F
  }
  
  return(list("ft_k_filt" = lista_ft_k_filt, "at_k_filt" = lista_at_k_filt,
              "Rt_k_filt" = lista_Rt_k_filt, "resp_media_esc" = lista_resp_med_esc, 
              "CI_inf" = lista_CI_inf, "CI_sup" = lista_CI_sup))
}
```



```{r}
res_dlm_suav <- suavizamiento_V_desc(datos_ej, G20, 39.5, list_interv)
```



```{r}
df_graficas_suav <- data.frame("fecha" = datos_ej %>% row.names(), "y_real" = datos_ej$y, 
           "resp_media" = res_dlm_suav$ft_k_filt %>% unlist(), "CI_inf" = res_dlm_suav$CI_inf %>% unlist(),
           "CI_sup" = res_dlm_suav$CI_sup %>% unlist()) %>% 
  mutate(fecha = as.numeric(fecha))
```


```{r}
ggplot(data = df_graficas_suav, aes(x = fecha)) +
  geom_point(aes(y = y_real, shape = "Observaciones"), size = 2) +
  geom_line(aes(y = resp_media, color = 'Respuesta media'), size = 1) +
  geom_line(aes(y = CI_inf), color = "blue", alpha = 0.3) +
  geom_line(aes(y = CI_sup), color = "blue", alpha = 0.3) + 
  geom_ribbon(aes(ymax = CI_sup, ymin = CI_inf, fill = 'Intervalo al 95%'), alpha = 0.3) +
  theme_bw() +
  scale_colour_manual(
    name = "", values = c("Intervalo al 95%" = "transparent",
                          "Respuesta media" = "black")) +
  scale_fill_manual(
    name = "",  values = c("Intervalo al 95%" = "blue",
                           "Respuesta media" = "transparent")) +
  theme(legend.position = "bottom") +
  labs(shape = "") +
  ylab('Ventas') +
  xlab('Fecha') +
  theme(axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title = element_text(size = 22),
        legend.text = element_text(size=20)) 

ggsave(filename = "graphs/teoria/intervencion/suavizamiento_interv.png", width = 11.7, height = 6)
```


Paso a paso


```{r}

#Valores conocidos de G30 y W30 no son necesarios por la intervención

#B. Priori de parámetros en t=30 intervenidos

a30_int 
R30_int 
```



```{r}
F30 <- c(1, 6.14705, 4.38513) #Variables explicativas en t=30. El 1 es para
                              #agregar el intercepto
S29 <- res_dlm$St[[10]] # Estimación de V en T=29
n29 <- 29.5 # Grados de libertad
#C. Pronóstico a un periodo.
f30 <- as.numeric(t(F30) %*% a30_int)
Q30 <- as.numeric(t(F30) %*% R30_int %*% F30 + S29)
f30
Q30
```

```{r}
c(qst(0.025, nu = n29, mu = f30, sigma = sqrt(Q30)),
  qst(0.975, nu = n29, mu = f30, sigma = sqrt(Q30)))
```

```{r}
#Valor observado de Y30:
Y30 <- 10.05563427
#D. Posterior en t=20
A30 <- R30_int %*% F30 / Q30
e30 <- Y30-f30
m30 <- a30_int + A30 %*% e30
n30 <- n29 + 1
S30 <- S29 + (S29/n30)*(e30^2/Q30-1)
C30 <- (S30/S29)*(R30_int-A30 %*% t(A30) * Q30)
m30
C30
```


Distribuciones filtradas

.
.

```{r}
R30 <- res_dlm_no_int$Rt[[11]]
# La descomposicion de Cholesky en R devuelve una triangular superior. Se transpone
# para hacerla triangular inferior para que coincida con la teoría presentada
U30 <- t(chol(R30_int))
Z30 <- t(chol(R30))
K30 <- U30 %*% solve(Z30)
G30_int <- K30 %*% G30
W30_int <- K30 %*% W30 %*% t(K30)
```


```{r}
C29 <- res_dlm$Ct[[10]]
m29 <- res_dlm$mt[[10]]
a39_menos_9 <- res_dlm_suav$at_k_filt[[11]]
R39_menos_9 <- res_dlm_suav$Rt_k_filt[[11]]

B29 <- C29 %*% t(G30_int) %*% solve(R30_int)
a39_menos_10 <- m29 + B29 %*% (a39_menos_9 - a30_int)
R39_menos_10 <- C29 + B29 %*% (R39_menos_9 - R30_int) %*% t(B29)

a39_menos_10
S39 <- res_dlm$St[[20]] # Estimación de V en T=39

S39/S29 * R39_menos_10
```

```{r}
F29 <- c(1, 6.131, 4.398) #Variables explicativas en t=29. 
t(F29) %*% a39_menos_10

S39/S29 * t(F29) %*% R39_menos_10 %*% F29
```



```{r}
U30 %*% t(U30)
Z30 %*% t(Z30)

a30 <- res_dlm_no_int$at[[11]] %>% as_vector()
h30 <- a30_int -K30 %*% a30
K30 %*% a30 + h30

K30 %*% R30 %*% t(K30)
R30_int
```





