---
title: "intervencion"
output: pdf_document
date: "2022-10-08"
---

\fontsize{15}{15}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(LaplacesDemon)
options(digits=4)
```

```{r}
#A. Posterior en t=19
m19 <- c(8, 0.35, -0.27)
C19 <- matrix(c(0.00002, 0.00001, -0.00002, 0.00001, 0.00004, -0.00001, -0.00002, 
                -0.00001, 0.00005), ncol = 3)

#Valores conocidos de G20 y W20
G20 <- matrix(c(1.05, 0, 0, 0, 1.02, 0, 0, 0, 0.99), ncol=3)
W20 <- matrix(c(0.00001, 0, 0, 0, 0.0001, -0.00001, 0, -0.00001, 0.00005), ncol=3)

#B. Priori de parámetros en t=20
a20 <- G20 %*% m19
R20 <- G20 %*% C19 %*% t(G20) + W20
a20
R20

a20_int <- c(8.4000, 0.7, -0.2673)
R20_int <- matrix(c(3.205e-05, 0.000010710, -2.0790e-05, 1.071e-05, 0.001, 
                    -2.0098e-05, -2.079e-05, -0.000020098, 9.9005e-05), ncol = 3)
```



```{r}
F20 <- c(1, 6.06093, 4.51018) #Variables explicativas en t=20. El 1 es para
                              #agregar el intercepto
S19 <- 0.002 # Estimación de V en T=19
n19 <- 19.5 # Grados de libertad
#C. Pronóstico a un periodo.
f20 <- as.numeric(t(F20) %*% a20_int)
Q20 <- as.numeric(t(F20) %*% R20_int %*% F20 + S19)
f20
Q20
```

```{r}
c(qst(0.025, nu = n19, mu = f20, sigma = sqrt(Q20)),
  qst(0.975, nu = n19, mu = f20, sigma = sqrt(Q20)))
```

```{r}
#Valor observado de Y20:
Y20 <- 11.05
#D. Posterior en t=20
A20 <- R20_int %*% F20 / Q20
e20 <- Y20-f20
m20 <- a20_int + A20 %*% e20
n20 <- n19 + 1
S20 <- S19 + (S19/n20)*(e20^2/Q20-1)
C20 <- (S20/S19)*(R20_int-A20 %*% t(A20) * Q20)
m20
C20
```

Distribuciones filtradas

```{r}
U20 <- chol(R20_int)
Z20 <- chol(R20)
K20 <- U20 %*% solve(Z20)
G20_int <- K20 %*% G20
W20_int <- K20 %*% W20 %*% t(K20)
```


```{r}
B19 <- C19 %*% t(G20_int) %*% solve(R20_int)
a20_menos_1 <- m19 + B19 %*% (m20 - a20_int)
R20_menos_1 <- C19 - B19 %*% (C20 - R20_int) %*% solve(B19)

a20_menos_1

S20/S19 * R20_menos_1
```

```{r}
F19 <- c(1, 6.05563	, 4.53957) #Variables explicativas en t=19. El 1 es para
                              #agregar el intercepto
t(F19) %*% a20_menos_1

S20/S19 * t(F19) %*% R20_menos_1 %*% F19
```
